# docker-compose build elk
#
# Run with:
# docker-compose up
version: '2'

services:
  elk:
    container_name: elk
    build: .
    ports:
       - "5601:5601"
       - "9200:9200"
       - "5044:5044"
    networks:
       - elk_net

networks:
  elk_net:
    driver: bridge
