filebeat.inputs:
 - type: log
   paths:
     - '/usr/share/dockerlogs/data/*/*.log'
   document_type: docker

processors:
   - decode_json_fields:
      when.regexp.message: '^{'
      fields: ["message"]
      target: ""
      overwrite_keys: true
   - add_docker_metadata: ~

output.logstash:
  enabled: true
  hosts: ["elk:5044"]

setup.kibana:
  host: "elk:5601"

logging.to_files: true
logging.to_syslog: false
